[settings]
minimum_release_age = "7d"

[tools]
node = "24.18.0"
pnpm = "11.10.0"

[tasks.setup]
run = [
  "pnpm install"
]

[tasks.build]
run = [
  "pnpm build"
]

[tasks.lint]
run = [
  "pnpm lint"
]
